version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5051:5051"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    ports:
      - "3306:3306"

